const categories = [
  {
    id: 1,
    name: "ЭЛЕКТРИКА",
    isDeleted: false,
    parentId: 0,
  },
  {
    id: 19,
    name: "БЕЗОПАСНОСТЬ",
    isDeleted: false,
    parentId: 0,
  },
  {
    id: 30,
    name: "КРЕПЁЖ",
    isDeleted: false,
    parentId: 0,
  },
  {
    id: 29,
    name: "ТЕЛЕКОМ и СКС",
    isDeleted: false,
    parentId: 0,
  },
  {
    id: 11,
    name: "СВЕТОТЕХНИКА",
    isDeleted: false,
    parentId: 0,
  },
  {
    id: 6,
    name: "Обогрев и вентиляция",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 10,
    name: "Щиты и шкафы",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 9,
    name: "Сопутствующие товары",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 8,
    name: "Розетки и выключатели",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 7,
    name: "Оборудование 6-10 кВ",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 5,
    name: "Низковольтное оборудование",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 4,
    name: "Кабели и провода",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 3,
    name: "Инструмент",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 2,
    name: "Изделия для электромонтажа",
    isDeleted: false,
    parentId: 1,
  },
  {
    id: 18,
    name: "Традиционные светильник",
    isDeleted: false,
    parentId: 11,
  },
  {
    id: 17,
    name: "Системы управления освещением",
    isDeleted: false,
    parentId: 11,
  },
  {
    id: 16,
    name: "Светильники светодиодные (LED)",
    isDeleted: false,
    parentId: 11,
  },
  {
    id: 15,
    name: "Металлоконструкции для уличного освещения",
    isDeleted: false,
    parentId: 11,
  },
  {
    id: 14,
    name: "Комплектующие и аксессуары для светильников",
    isDeleted: false,
    parentId: 11,
  },
  {
    id: 13,
    name: "Источники света (лампы)",
    isDeleted: false,
    parentId: 11,
  },
  {
    id: 12,
    name: "Бактерицидные облучатели и лампы",
    isDeleted: false,
    parentId: 11,
  },
  {
    id: 28,
    name: "Шлагбаумы и автоматика для ворот",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 27,
    name: "Системы оповещения (СОУЭ)",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 26,
    name: "Системы контроля доступа (СКУД)",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 25,
    name: "Системы видеонаблюдения (CCTV)",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 24,
    name: "Серверы, мониторы, комплектующие ПК",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 23,
    name: "Охранно-пожарная сигнализация (ОПС)",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 22,
    name: "Кабельно-проводниковая продукция",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 21,
    name: "Домофоны и переговорные устройства",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 20,
    name: "Автоматизация зданий и Телефония",
    isDeleted: false,
    parentId: 19,
  },
  {
    id: 38,
    name: "Саморезы, шурупы",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 39,
    name: "Такелаж",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 40,
    name: "Тросы, цепи, веревки, проволока",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 41,
    name: "Хомуты и сантехнический крепеж",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 37,
    name: "Перфорированный крепеж",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 36,
    name: "Метрический крепеж",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 35,
    name: "Заклепки",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 34,
    name: "Дюбельная техника",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 33,
    name: "Гвозди",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 32,
    name: "Биты, буры, инструмент",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 31,
    name: "Анкерная техника",
    isDeleted: false,
    parentId: 30,
  },
  {
    id: 42,
    name: "Удаленная категория 1",
    isDeleted: true,
    parentId: 30,
  },
  {
    id: 141,
    name: "Удаленная категория 2",
    isDeleted: true,
    parentId: 30,
  },
  {
    id: 142,
    name: "Удаленная категория 3",
    isDeleted: true,
    parentId: 30,
  },
  {
    id: 143,
    name: "Удаленная категория 4",
    isDeleted: true,
    parentId: 30,
  },
];

export default categories;
